[package]
name = "libcrux-rsa"
description = "Formally verified RSA signature library"

version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true

[features]
expose-hacl = []

[dependencies]
libcrux-hacl-rs = { version = "=0.0.2-beta.3", path = "../hacl-rs" }
libcrux-traits = { version = "=0.0.2-beta.3", path = "../traits/" }
libcrux-macros = { version = "=0.0.2-beta.3", path = "../macros" }
libcrux-sha2 = { version = "=0.0.2-beta.3", path = "../sha2", features = [
    "expose-hacl",
] }

[dev-dependencies]
wycheproof = "0.6.0"
