name: Workspace - Checks

on:
  merge_group:
    # keep workflow specific if GH Actions adds more types in the future
    types: ["checks-requested"]
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 🧹 Cargo fmt
        run: cargo fmt --all -- --check
