[package]
name = "libcrux-secrets"
version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true
description = "Libcrux utilities for working with secrets"
exclude = ["/proofs"]

[dependencies]
hax-lib.workspace = true

[features]
check-secret-independence = []
default = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(hax)', 'cfg(eurydice)'] }

[dev-dependencies]
criterion = "0.5.1"
